# site settings
title: Arkos
subtitle: QOTY
email: priyangshu@cmi.ac.in
description: What could be responsible for the rise of male virginity? 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://Arkos11.github.io" # the base hostname & protocol for your site
author:Arkos
street_address: Rajarhat
city: Kolkata
state: TN
zip_code: 700135
country: Halaand
phone: (+91) 7439376632

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Arkos11.github.io
  GitLab:
  Google-Plus: nah nobody uses g+ anymore
  Instagram:cringe
  LinkedIn: no
  Twitter: https://twitter.com/lp6taloscharis
  Facebook: old
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
