base_url = "https://arkos11.github.io"
title = "My Site"
description = "Writing, notes, links, and projects."
default_language = "en"
compile_sass = true
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
author = "Arkos"
subtitle = "Writing, notes, and projects"
show_feed_link = true
